export type LarkCapabilityRisk = 'read' | 'write';

export type LarkCapability = {
  allowedFlags: readonly string[];
  description: string;
  domain: string;
  id: string;
  identity: 'user' | 'bot' | 'auto';
  risk: LarkCapabilityRisk;
  shortcut: string;
  supportsFormat?: boolean;
  timeoutMs: number;
};

const READ_TIMEOUT_MS = 45_000;
const WRITE_TIMEOUT_MS = 60_000;

export const LARK_CAPABILITIES = [
  {
    id: 'contact_search_user',
    domain: 'contact',
    shortcut: '+search-user',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书联系人，支持姓名、邮箱或 open_id 查询。',
    allowedFlags: [
      'query',
      'queries',
      'user-ids',
      'page-size',
      'lang',
      'has-chatted',
      'exclude-external-users',
      'has-enterprise-email',
      'left-organization',
    ],
  },
  {
    id: 'contact_get_user',
    domain: 'contact',
    shortcut: '+get-user',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取当前用户或指定飞书用户资料。',
    allowedFlags: ['user-id', 'user-id-type'],
  },
  {
    id: 'calendar_agenda',
    domain: 'calendar',
    shortcut: '+agenda',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查看指定日期范围的飞书日程。',
    allowedFlags: ['calendar-id', 'start', 'end'],
  },
  {
    id: 'calendar_freebusy',
    domain: 'calendar',
    shortcut: '+freebusy',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查询用户忙闲状态。',
    allowedFlags: ['user-id', 'start', 'end'],
  },
  {
    id: 'calendar_suggestion',
    domain: 'calendar',
    shortcut: '+suggestion',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '根据参会人和时间范围推荐可用会议时间。',
    allowedFlags: ['attendee-ids', 'duration-minutes', 'start', 'end', 'timezone', 'exclude', 'event-rrule'],
  },
  {
    id: 'im_chat_list',
    domain: 'im',
    shortcut: '+chat-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出当前用户可见群聊。',
    allowedFlags: ['page-size', 'page-token', 'sort-type', 'user-id-type', 'exclude-muted'],
  },
  {
    id: 'im_chat_messages_list',
    domain: 'im',
    shortcut: '+chat-messages-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取指定群聊或单聊的消息列表。',
    allowedFlags: ['chat-id', 'user-id', 'start', 'end', 'page-size', 'page-token', 'sort'],
  },
  {
    id: 'im_messages_mget',
    domain: 'im',
    shortcut: '+messages-mget',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '按 message_id 批量读取消息详情。',
    allowedFlags: ['message-ids'],
  },
  {
    id: 'im_threads_messages_list',
    domain: 'im',
    shortcut: '+threads-messages-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取飞书消息线程内的回复列表。',
    allowedFlags: ['thread', 'page-size', 'page-token', 'sort'],
  },
  {
    id: 'drive_search',
    domain: 'drive',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书云空间、文档、知识库和表格文件。',
    allowedFlags: [
      'query',
      'page-size',
      'page-token',
      'doc-types',
      'sort',
      'mine',
      'only-title',
      'only-comment',
      'creator-ids',
      'chat-ids',
      'space-ids',
      'folder-tokens',
      'created-since',
      'created-until',
      'edited-since',
      'edited-until',
      'opened-since',
      'opened-until',
      'commented-since',
      'commented-until',
      'sharer-ids',
    ],
  },
  {
    id: 'wiki_space_list',
    domain: 'wiki',
    shortcut: '+space-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出当前用户可访问的飞书知识库空间。',
    allowedFlags: ['page-size', 'page-token', 'page-all', 'page-limit'],
  },
  {
    id: 'wiki_node_list',
    domain: 'wiki',
    shortcut: '+node-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出飞书知识库节点。',
    allowedFlags: ['space-id', 'parent-node-token', 'page-size', 'page-token', 'page-all', 'page-limit'],
  },
  {
    id: 'sheets_info',
    domain: 'sheets',
    shortcut: '+info',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查看飞书电子表格和工作表信息。',
    allowedFlags: ['spreadsheet-token', 'url'],
    supportsFormat: false,
  },
  {
    id: 'sheets_read',
    domain: 'sheets',
    shortcut: '+read',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取飞书电子表格单元格范围。',
    allowedFlags: ['spreadsheet-token', 'url', 'sheet-id', 'range', 'value-render-option'],
    supportsFormat: false,
  },
  {
    id: 'sheets_find',
    domain: 'sheets',
    shortcut: '+find',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '在飞书电子表格中查找单元格内容。',
    allowedFlags: [
      'spreadsheet-token',
      'url',
      'sheet-id',
      'range',
      'find',
      'ignore-case',
      'include-formulas',
      'match-entire-cell',
      'search-by-regex',
    ],
    supportsFormat: false,
  },
  {
    id: 'mail_triage',
    domain: 'mail',
    shortcut: '+triage',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '浏览或搜索飞书邮箱摘要。',
    allowedFlags: ['query', 'filter', 'mailbox', 'max', 'page-size', 'page-token', 'labels'],
  },
  {
    id: 'mail_message',
    domain: 'mail',
    shortcut: '+message',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取单封飞书邮件正文。',
    allowedFlags: ['message-id', 'mailbox', 'html', 'print-output-schema'],
  },
  {
    id: 'mail_thread',
    domain: 'mail',
    shortcut: '+thread',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取飞书邮件会话线程。',
    allowedFlags: ['thread-id', 'mailbox', 'html', 'include-spam-trash', 'print-output-schema'],
  },
  {
    id: 'minutes_search',
    domain: 'minutes',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书妙记。',
    allowedFlags: ['query', 'owner-ids', 'participant-ids', 'start', 'end', 'page-size', 'page-token'],
  },
  {
    id: 'vc_search',
    domain: 'vc',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书视频会议记录。',
    allowedFlags: ['query', 'organizer-ids', 'participant-ids', 'room-ids', 'start', 'end', 'page-size', 'page-token'],
  },
  {
    id: 'vc_notes',
    domain: 'vc',
    shortcut: '+notes',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查询会议纪要产物。',
    allowedFlags: ['meeting-ids', 'minute-tokens', 'calendar-event-ids'],
  },
  {
    id: 'task_search',
    domain: 'task',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书任务。',
    allowedFlags: [
      'query',
      'assignee',
      'creator',
      'follower',
      'completed',
      'due',
      'page-all',
      'page-limit',
      'page-token',
    ],
  },
  {
    id: 'task_get_my_tasks',
    domain: 'task',
    shortcut: '+get-my-tasks',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出分配给我的飞书任务。',
    allowedFlags: ['query', 'complete', 'created_at', 'due-start', 'due-end', 'page-all', 'page-limit', 'page-token'],
  },
  {
    id: 'task_get_related_tasks',
    domain: 'task',
    shortcut: '+get-related-tasks',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出与我相关的飞书任务。',
    allowedFlags: ['created-by-me', 'followed-by-me', 'include-complete', 'page-all', 'page-limit', 'page-token'],
  },
  {
    id: 'okr_cycle_list',
    domain: 'okr',
    shortcut: '+cycle-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出指定用户的 OKR 周期。',
    allowedFlags: ['user-id', 'user-id-type', 'time-range'],
  },
  {
    id: 'okr_cycle_detail',
    domain: 'okr',
    shortcut: '+cycle-detail',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查看 OKR 周期下的目标和关键结果。',
    allowedFlags: ['cycle-id'],
  },
  {
    id: 'calendar_create',
    domain: 'calendar',
    shortcut: '+create',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '创建飞书日程。',
    allowedFlags: ['calendar-id', 'summary', 'description', 'start', 'end', 'attendee-ids', 'rrule', 'dry-run'],
  },
  {
    id: 'calendar_update',
    domain: 'calendar',
    shortcut: '+update',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '更新飞书日程。',
    allowedFlags: [
      'calendar-id',
      'event-id',
      'summary',
      'description',
      'start',
      'end',
      'add-attendee-ids',
      'remove-attendee-ids',
      'rrule',
      'notify',
      'dry-run',
    ],
  },
  {
    id: 'calendar_rsvp',
    domain: 'calendar',
    shortcut: '+rsvp',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '回复飞书日程邀请。',
    allowedFlags: ['calendar-id', 'event-id', 'rsvp-status', 'dry-run'],
  },
  {
    id: 'task_create',
    domain: 'task',
    shortcut: '+create',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '创建飞书任务。',
    allowedFlags: [
      'summary',
      'description',
      'due',
      'assignee',
      'follower',
      'tasklist-id',
      'data',
      'idempotency-key',
      'dry-run',
    ],
  },
  {
    id: 'task_update',
    domain: 'task',
    shortcut: '+update',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '更新飞书任务。',
    allowedFlags: ['task-id', 'summary', 'description', 'due', 'data', 'dry-run'],
  },
  {
    id: 'task_complete',
    domain: 'task',
    shortcut: '+complete',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '完成飞书任务。',
    allowedFlags: ['task-id', 'dry-run'],
  },
  {
    id: 'task_comment',
    domain: 'task',
    shortcut: '+comment',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '给飞书任务添加评论。',
    allowedFlags: ['task-id', 'content', 'dry-run'],
  },
  {
    id: 'docs_update',
    domain: 'docs',
    shortcut: '+update',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '更新飞书文档内容。',
    allowedFlags: [
      'api-version',
      'doc',
      'markdown',
      'mode',
      'new-title',
      'selection-by-title',
      'selection-with-ellipsis',
      'dry-run',
    ],
    supportsFormat: false,
  },
  {
    id: 'drive_add_comment',
    domain: 'drive',
    shortcut: '+add-comment',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '给飞书文档、表格或幻灯片添加评论。',
    allowedFlags: ['doc', 'type', 'content', 'block-id', 'selection-with-ellipsis', 'full-comment', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'sheets_append',
    domain: 'sheets',
    shortcut: '+append',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '向飞书电子表格追加行数据。',
    allowedFlags: ['spreadsheet-token', 'url', 'sheet-id', 'range', 'values', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'sheets_write',
    domain: 'sheets',
    shortcut: '+write',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '覆盖写入飞书电子表格单元格。',
    allowedFlags: ['spreadsheet-token', 'url', 'sheet-id', 'range', 'values', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'mail_draft_create',
    domain: 'mail',
    shortcut: '+draft-create',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '创建飞书邮箱草稿，不直接发送。',
    allowedFlags: [
      'to',
      'cc',
      'bcc',
      'subject',
      'body',
      'from',
      'mailbox',
      'plain-text',
      'priority',
      'request-receipt',
      'signature-id',
      'template-id',
      'event-summary',
      'event-start',
      'event-end',
      'event-location',
      'dry-run',
    ],
  },
  {
    id: 'mail_reply',
    domain: 'mail',
    shortcut: '+reply',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '创建飞书邮箱回复草稿，不直接发送。',
    allowedFlags: [
      'message-id',
      'to',
      'cc',
      'bcc',
      'subject',
      'body',
      'from',
      'mailbox',
      'plain-text',
      'priority',
      'request-receipt',
      'signature-id',
      'template-id',
      'event-summary',
      'event-start',
      'event-end',
      'event-location',
      'dry-run',
    ],
  },
  {
    id: 'mail_forward',
    domain: 'mail',
    shortcut: '+forward',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '创建飞书邮箱转发草稿，不直接发送。',
    allowedFlags: [
      'message-id',
      'to',
      'cc',
      'bcc',
      'subject',
      'body',
      'from',
      'mailbox',
      'plain-text',
      'priority',
      'request-receipt',
      'signature-id',
      'template-id',
      'event-summary',
      'event-start',
      'event-end',
      'event-location',
      'dry-run',
    ],
  },
  {
    id: 'drive_upload',
    domain: 'drive',
    shortcut: '+upload',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '上传本地文件到飞书云空间。真实执行前必须由用户明确选择或确认文件路径。',
    allowedFlags: ['file', 'name', 'folder-token', 'wiki-token', 'file-token', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'drive_download',
    domain: 'drive',
    shortcut: '+download',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '下载飞书云空间文件到本地。真实执行前必须确认输出路径。',
    allowedFlags: ['file-token', 'output', 'overwrite', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'drive_import',
    domain: 'drive',
    shortcut: '+import',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '导入本地文件为飞书云文档。真实执行前必须由用户明确选择或确认文件路径。',
    allowedFlags: ['file', 'name', 'folder-token', 'type', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'drive_export_download',
    domain: 'drive',
    shortcut: '+export-download',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '下载飞书导出任务产物到本地。真实执行前必须确认输出目录。',
    allowedFlags: ['file-token', 'file-name', 'output-dir', 'overwrite', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'sheets_create',
    domain: 'sheets',
    shortcut: '+create',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '创建飞书电子表格。',
    allowedFlags: ['title', 'headers', 'data', 'folder-token', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'sheets_create_sheet',
    domain: 'sheets',
    shortcut: '+create-sheet',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '在已有飞书电子表格中创建工作表。',
    allowedFlags: ['spreadsheet-token', 'url', 'title', 'index', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'sheets_export',
    domain: 'sheets',
    shortcut: '+export',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '导出飞书电子表格到本地文件。真实执行前必须确认输出路径。',
    allowedFlags: ['spreadsheet-token', 'url', 'file-extension', 'sheet-id', 'output-path', 'dry-run'],
    supportsFormat: false,
  },
  {
    id: 'base_table_list',
    domain: 'base',
    shortcut: '+table-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出飞书多维表格中的数据表。',
    allowedFlags: ['base-token', 'limit', 'offset'],
    supportsFormat: false,
  },
  {
    id: 'base_field_list',
    domain: 'base',
    shortcut: '+field-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出飞书多维表格数据表字段。',
    allowedFlags: ['base-token', 'table-id', 'limit', 'offset'],
    supportsFormat: false,
  },
  {
    id: 'base_record_search',
    domain: 'base',
    shortcut: '+record-search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '按关键词搜索飞书多维表格记录。',
    allowedFlags: ['base-token', 'table-id', 'json'],
  },
  {
    id: 'base_record_list',
    domain: 'base',
    shortcut: '+record-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出飞书多维表格记录。',
    allowedFlags: ['base-token', 'table-id', 'field-id', 'view-id', 'offset', 'limit'],
  },
  {
    id: 'base_data_query',
    domain: 'base',
    shortcut: '+data-query',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '使用 JSON DSL 查询和分析飞书多维表格数据。',
    allowedFlags: ['base-token', 'dsl'],
    supportsFormat: false,
  },
  {
    id: 'base_record_upsert',
    domain: 'base',
    shortcut: '+record-upsert',
    identity: 'user',
    risk: 'write',
    timeoutMs: WRITE_TIMEOUT_MS,
    description: '创建或更新飞书多维表格记录。',
    allowedFlags: ['base-token', 'table-id', 'record-id', 'json', 'dry-run'],
    supportsFormat: false,
  },
] as const satisfies readonly LarkCapability[];

export type LarkCapabilityId = (typeof LARK_CAPABILITIES)[number]['id'];

export function getLarkCapability(id: string): LarkCapability | undefined {
  return LARK_CAPABILITIES.find((capability) => capability.id === id);
}

export function listLarkCapabilities(): LarkCapability[] {
  return [...LARK_CAPABILITIES];
}
