export type LarkCapabilityRisk = 'read' | 'write';

export type LarkCapability = {
  allowedFlags: readonly string[];
  description: string;
  domain: string;
  id: string;
  identity: 'user' | 'bot' | 'auto';
  risk: LarkCapabilityRisk;
  shortcut: string;
  supportsFormat?: boolean;
  timeoutMs: number;
};

const READ_TIMEOUT_MS = 45_000;

export const LARK_CAPABILITIES = [
  {
    id: 'contact_search_user',
    domain: 'contact',
    shortcut: '+search-user',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书联系人，支持姓名、邮箱或 open_id 查询。',
    allowedFlags: [
      'query',
      'queries',
      'user-ids',
      'page-size',
      'lang',
      'has-chatted',
      'exclude-external-users',
      'has-enterprise-email',
      'left-organization',
    ],
  },
  {
    id: 'contact_get_user',
    domain: 'contact',
    shortcut: '+get-user',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取当前用户或指定飞书用户资料。',
    allowedFlags: ['user-id', 'user-id-type'],
  },
  {
    id: 'calendar_agenda',
    domain: 'calendar',
    shortcut: '+agenda',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查看指定日期范围的飞书日程。',
    allowedFlags: ['calendar-id', 'start', 'end'],
  },
  {
    id: 'calendar_freebusy',
    domain: 'calendar',
    shortcut: '+freebusy',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查询用户忙闲状态。',
    allowedFlags: ['user-id', 'start', 'end'],
  },
  {
    id: 'calendar_suggestion',
    domain: 'calendar',
    shortcut: '+suggestion',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '根据参会人和时间范围推荐可用会议时间。',
    allowedFlags: ['attendee-ids', 'duration-minutes', 'start', 'end', 'timezone', 'exclude', 'event-rrule'],
  },
  {
    id: 'im_chat_list',
    domain: 'im',
    shortcut: '+chat-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出当前用户可见群聊。',
    allowedFlags: ['page-size', 'page-token', 'sort-type', 'user-id-type', 'exclude-muted'],
  },
  {
    id: 'im_chat_messages_list',
    domain: 'im',
    shortcut: '+chat-messages-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取指定群聊或单聊的消息列表。',
    allowedFlags: ['chat-id', 'user-id', 'start', 'end', 'page-size', 'page-token', 'sort'],
  },
  {
    id: 'im_messages_mget',
    domain: 'im',
    shortcut: '+messages-mget',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '按 message_id 批量读取消息详情。',
    allowedFlags: ['message-ids'],
  },
  {
    id: 'im_threads_messages_list',
    domain: 'im',
    shortcut: '+threads-messages-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取飞书消息线程内的回复列表。',
    allowedFlags: ['thread', 'page-size', 'page-token', 'sort'],
  },
  {
    id: 'drive_search',
    domain: 'drive',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书云空间、文档、知识库和表格文件。',
    allowedFlags: [
      'query',
      'page-size',
      'page-token',
      'doc-types',
      'sort',
      'mine',
      'only-title',
      'only-comment',
      'creator-ids',
      'chat-ids',
      'space-ids',
      'folder-tokens',
      'created-since',
      'created-until',
      'edited-since',
      'edited-until',
      'opened-since',
      'opened-until',
      'commented-since',
      'commented-until',
      'sharer-ids',
    ],
  },
  {
    id: 'wiki_space_list',
    domain: 'wiki',
    shortcut: '+space-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出当前用户可访问的飞书知识库空间。',
    allowedFlags: ['page-size', 'page-token', 'page-all', 'page-limit'],
  },
  {
    id: 'wiki_node_list',
    domain: 'wiki',
    shortcut: '+node-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出飞书知识库节点。',
    allowedFlags: ['space-id', 'parent-node-token', 'page-size', 'page-token', 'page-all', 'page-limit'],
  },
  {
    id: 'sheets_info',
    domain: 'sheets',
    shortcut: '+info',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查看飞书电子表格和工作表信息。',
    allowedFlags: ['spreadsheet-token', 'url'],
    supportsFormat: false,
  },
  {
    id: 'sheets_read',
    domain: 'sheets',
    shortcut: '+read',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取飞书电子表格单元格范围。',
    allowedFlags: ['spreadsheet-token', 'url', 'sheet-id', 'range', 'value-render-option'],
    supportsFormat: false,
  },
  {
    id: 'sheets_find',
    domain: 'sheets',
    shortcut: '+find',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '在飞书电子表格中查找单元格内容。',
    allowedFlags: [
      'spreadsheet-token',
      'url',
      'sheet-id',
      'range',
      'find',
      'ignore-case',
      'include-formulas',
      'match-entire-cell',
      'search-by-regex',
    ],
    supportsFormat: false,
  },
  {
    id: 'mail_triage',
    domain: 'mail',
    shortcut: '+triage',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '浏览或搜索飞书邮箱摘要。',
    allowedFlags: ['query', 'filter', 'mailbox', 'max', 'page-size', 'page-token', 'labels'],
  },
  {
    id: 'mail_message',
    domain: 'mail',
    shortcut: '+message',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取单封飞书邮件正文。',
    allowedFlags: ['message-id', 'mailbox', 'html', 'print-output-schema'],
  },
  {
    id: 'mail_thread',
    domain: 'mail',
    shortcut: '+thread',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '读取飞书邮件会话线程。',
    allowedFlags: ['thread-id', 'mailbox', 'html', 'include-spam-trash', 'print-output-schema'],
  },
  {
    id: 'minutes_search',
    domain: 'minutes',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书妙记。',
    allowedFlags: ['query', 'owner-ids', 'participant-ids', 'start', 'end', 'page-size', 'page-token'],
  },
  {
    id: 'vc_search',
    domain: 'vc',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书视频会议记录。',
    allowedFlags: ['query', 'organizer-ids', 'participant-ids', 'room-ids', 'start', 'end', 'page-size', 'page-token'],
  },
  {
    id: 'vc_notes',
    domain: 'vc',
    shortcut: '+notes',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查询会议纪要产物。',
    allowedFlags: ['meeting-ids', 'minute-tokens', 'calendar-event-ids'],
  },
  {
    id: 'task_search',
    domain: 'task',
    shortcut: '+search',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '搜索飞书任务。',
    allowedFlags: [
      'query',
      'assignee',
      'creator',
      'follower',
      'completed',
      'due',
      'page-all',
      'page-limit',
      'page-token',
    ],
  },
  {
    id: 'task_get_my_tasks',
    domain: 'task',
    shortcut: '+get-my-tasks',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出分配给我的飞书任务。',
    allowedFlags: ['query', 'complete', 'created_at', 'due-start', 'due-end', 'page-all', 'page-limit', 'page-token'],
  },
  {
    id: 'task_get_related_tasks',
    domain: 'task',
    shortcut: '+get-related-tasks',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出与我相关的飞书任务。',
    allowedFlags: ['created-by-me', 'followed-by-me', 'include-complete', 'page-all', 'page-limit', 'page-token'],
  },
  {
    id: 'okr_cycle_list',
    domain: 'okr',
    shortcut: '+cycle-list',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '列出指定用户的 OKR 周期。',
    allowedFlags: ['user-id', 'user-id-type', 'time-range'],
  },
  {
    id: 'okr_cycle_detail',
    domain: 'okr',
    shortcut: '+cycle-detail',
    identity: 'user',
    risk: 'read',
    timeoutMs: READ_TIMEOUT_MS,
    description: '查看 OKR 周期下的目标和关键结果。',
    allowedFlags: ['cycle-id'],
  },
] as const satisfies readonly LarkCapability[];

export type LarkCapabilityId = (typeof LARK_CAPABILITIES)[number]['id'];

export function getLarkCapability(id: string): LarkCapability | undefined {
  return LARK_CAPABILITIES.find((capability) => capability.id === id);
}

export function listLarkCapabilities(): LarkCapability[] {
  return [...LARK_CAPABILITIES];
}
